name: List services in GCP
on:
  push:
    branches:
      - master

permissions:
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: projects/691947957481/locations/global/workloadIdentityPools/github-actions/providers/github-actions-oidc 
          service_account: github-actions-workflow@test-392414.iam.gserviceaccount.com
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs}}"
        gcloud services list
