name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: "test-392414"
  CLUSTER_NAME: "my-gke-cluster"
  ZONE: "asia-south2-a"

jobs:
  deploy:
    runs-on: rhel-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/$PROJECT_ID/<IMAGE_NAME>:${{ env.TAG_NAME }}

      - name: Deploy to GKE
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: $PROJECT_ID
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Configure kubectl
        run: |
          gcloud config set project $PROJECT_ID
          gcloud config set compute/zone $ZONE
          gcloud container clusters get-credentials $CLUSTER_NAME

      - name: Apply deployment
        run: |
          kubectl apply -f deployment.yml
