name: List services in GCP
on:
  push:
    branches:
      - master

permissions:
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: self-hosted
    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path}}"
        gcloud services list
